---
language: python
python:
  - "3.6"
services: docker

env:
  global:
    - ROLE_NAME: zulu-openjdk
    - ROLE_REMOTE_NAME: zulu_openjdk
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    #- MOLECULE_DISTRO: ubuntu1804
    #- MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9


install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME jeduoliveira.$ROLE_REMOTE_NAME
  - cd jeduoliveira.$ROLE_REMOTE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
