---
language: python
python:
  - "3.6"
services: docker

env:
  global:
    - ROLE_NAME: zulu_openjdk
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME jeduoliveira.$ROLE_NAME
  - cd jeduoliveira.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
