---
language: python
python: "3.6"

services:
  - docker

env:
  global:
    - ROLE_NAME: zulu-openjdk

  matrix:
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME jeduoliveira.$ROLE_NAME
  - cd jeduoliveira.$ROLE_NAME

script:
  - molecule test

sudo: required

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
