---
- name: Include variables.
  include_vars: vars.yml

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define zulu_key_url.
  set_fact:
    zulu_key_url: "{{ __zulu_key_url }}"
  when: zulu_key_url is not defined

- name: Define zulu_repo_url
  set_fact:
    zulu_repo_url: "{{ __zulu_repo_url }}"
  when: zulu_repo_url is not defined

- name: Define zulu_package_name.
  set_fact:
    zulu_package_name: "{{ __zulu_package_name }}"
  when: zulu_package_name is not defined

- include_tasks: setup.yml

- name: set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0755
  environment:
    JAVA_HOME: "{{ java_home }}"
  when: java_home is defined and java_home
