---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define zulu_packages.
  set_fact:
    zulu_packages: "{{ __zulu_packages }}"
  when: zulu_packages is not defined
