---
- name: Include variables.
  include_vars: vars.yml

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define zulu_version.
  set_fact:
    zulu_version: "{{ __zulu_version }}"
  when: zulu_version is not defined

- name: Define Zulu Release.
  set_fact:
    zulu_release: "{{ __zulu_release }}"
  when: zulu_release is not defined

- name: Define zulu_jdk_version.
  set_fact:
    zulu_jdk_version: "{{ __zulu_jdk_version }}"
  when: zulu_jdk_version is not defined

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: set java home as environment variable
  blockinfile:
    insertafter: EOF
    path: /etc/environment
    block: "export JAVA_HOME={{ java_home }}"
  when: java_home is defined and java_home
