---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define zulu_version.
  set_fact:
    zulu_version: "{{ __zulu_version }}"
  when: zulu_version is not defined

- name: Define jdk_version.
  set_fact:
    jdk_version: "{{ __jdk_version }}"
  when: jdk_version is not defined

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
