---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
  when:
    - ansible_distribution == 'Ubuntu'

- name: install the zulu jdk
  apt:
    deb: "https://cdn.azul.com/zulu/bin/zulu{{ zulu_version }}-ca-{{ jdk_version }}-linux_amd64.deb"
    state: present
  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US:en
    LC_ALL: en_US.UTF-8
