---


- name: hack to resolve Problem with MergeList Issue
  shell: 'find /var/lib/apt/lists -maxdepth 1 -type f -exec rm -v {} \;'
  become: yes

- name: update softwares
  apt:
    update_cache: yes

- name: install the zulu jdk
  apt:
    deb: "{{ zulu_url_repo }}"
    state: present

  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US:en
    LC_ALL: en_US.UTF-8
