---

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://www.azul.com/files/0xB1998361219BD9C9.txt

- name: Install Zulu JDK rpm
  yum:
    name: https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm
    state: present
    validate_certs: false
  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US:en
    LC_ALL: en_US.UTF-8
