---


- name: hack to resolve Problem with MergeList Issue
  sudo: true
  shell: 'find /var/lib/apt/lists -maxdepth 1 -type f -exec rm -v {} \;'

- name: update softwares 
  apt: 
    update_cache: yes

- name: install the zulu jdk
  apt:
    deb: "{{ zulu_url_repo }}"
    state: present
  become: yes
  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US:en
    LC_ALL: en_US.UTF-8
