---

- name: import a key zulu
  ansible.builtin.rpm_key:
    state: present
    key: "{{ zulu_url_key }}"

- name: install zulu-repo
  yum:
    name: "{{ zulu_repo_url }}"
    state: present

- name: install zulu-jre-headless
  yum:
    name: "{{ zulu_package_name }}"
    state: present
    validate_certs: false
  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US:en
    LC_ALL: en_US.UTF-8
