---

- name: Add an apt key by id from a keyserver
  apt_key:
    id: "0xB1998361219BD9C9"
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: install repo Ubuntu
  apt_repository:
    repo: deb http://repos.azulsystems.com/ubuntu stable main
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: True
    update_cache: yes
    cache_valid_time: 86400

- name: install the zulu jdk
  apt:
    name: "https://cdn.azul.com/zulu/bin/zulu{{ zulu_verison }}-ca-{{ jdk_version }}-linux_amd64.deb"
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US:en
    LC_ALL: en_US.UTF-8
